#!/usr/local/bin/bash

c00=$'\e[0;30m'
c01=$'\e[0;31m'
c02=$'\e[0;32m'
c03=$'\e[0;33m'
c04=$'\e[0;34m'
c05=$'\e[0;35m'
c06=$'\e[0;36m'
c07=$'\e[0;37m'
c08=$'\e[1;30m'
c09=$'\e[1;31m'
c10=$'\e[1;32m'
c11=$'\e[1;33m'
c12=$'\e[1;34m'
c13=$'\e[1;35m'
c14=$'\e[1;36m'
c15=$'\e[1;37m'

f0=$'\e[1;30m'
f1=$'\e[1;37m'
f2=$'\e[0;37m'

kernel=$(uname -mv)
cpuspe=$(cpuinfo | grep -v ! | awk '/CPU / {print $3$4$5$6$7$8}')

system=$(uname -s)

if [ -n "$DISPLAY" ]; then
    wmname=$(xprop -root _NET_WM_NAME|cut -d\" -f2)
    termfn=$(cat $HOME/.Xdefaults | grep -v ! | awk '/URxvt.font/ {print $3}')
    systfn=$(sed -n 's/^[gtk].*font.*"\(.*\)".*$/\1/p' ~/.gtkrc-2.0)
else
    wmname="none"
    termfn="none"
    systfn="none"
fi
wmname="bspwm"

pkgnum=$(pkg_info | wc -l | awk '{sub(" ", "");print $1}')
version=$(uname -r)

mem=$(top -1 1 | awk '/Real:/ {print $3}' | sed 's/M.*//')
myblog="https://github.com/zr0/n3gr0bsd"

cat << EOF

${c00}▉▉  | ${c15}OS ${f0}........... $f2$system
${c08}  ▉▉| ${c15}name ${f0}......... $f2$HOSTNAME
${c01}▉▉  | ${c15}verison${f0}....... $f2$version
${c09}  ▉▉| ${c15}packages ${f0}..... $f2$pkgnum
${c02}▉▉  | 
${c10}  ▉▉| ${c15}wm ${f0}........... $f2$wmname
${c03}▉▉  | ${c15}shell ${f0}........ $f2$SHELL
${c11}  ▉▉| ${c15}terminal ${f0}..... $f2$TERM
${c04}▉▉  | ${c15}term font ${f0}.... $f2$termfn
${c12}  ▉▉| ${c15}system font ${f0}.. $f2$systfn
${c05}▉▉  | 
${c13}  ▉▉| ${c15}ram ${f0}.......... $f2$mem
${c06}▉▉  | ${c15}kernel ${f0}....... $f2$kernel
${c14}  ▉▉| ${c15}processor ${f0}.... $f2$cpuspe
${c07}▉▉  | 
${c15}  ▉▉| ${c15}website ${f0}...... $f2$myblog

EOF
